// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "cellar": Application User Types
//
// Command:
// $ goagen
// --design=cellar/design
// --out=$(GOPATH)/src/cellar
// --version=v1.2.0-dirty

package app
